version: '3.8'

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3333
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./app/backend:/app
      - /app/node_modules
