services:
  nextjs:
    build:
      context: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - backend

  backend:
    build:
      context: ./app/backend
    ports:
      - "3333:3333"
    volumes:
      - ./app/backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
